---
title: "Clustering"
author: "Rochelle Terman"
date: "July 31, 2015"
output: html_document
---

Note: Tried this with machiavelli and women. women got better results.

### Setup Environment

First let's load our required packages.

```{r}
setwd("~/Dropbox/berkeley/Dissertation/Data and Analyais/Git Repos/text-analysis-dhbsi")
rm(list=ls())
library(RTextTools)
```

## 0. Prepare Data

```{r}
docs <- Corpus(DirSource("Data/British_Fiction/Selection"))
docs
dtm <- DocumentTermMatrix(docs)
            
# note that stemming / weighting really affects stuff here. Change it up to see.
dtm <- DocumentTermMatrix(docs,
           control = list(weighting =function(x) weightTfIdf(x, normalize = TRUE),
                          stopwords = T,
                          tolower = TRUE,
                          removeNumbers = TRUE,
                          removePunctuation = TRUE,
                          stemming=TRUE))
dim(dtm)
inspect(dtm[,100:104])
dtm.m <- as.matrix(dtm)
```

##Euclidean Distance and hierarchical clustering

```{r}
d <- dist(dtm.m, method = "euclidean")
plot(hclust(d))
```

## cosine similarity

```{r]}
library(lsa)
dtm.t <- t(dtm.m)
d <- cosine(dtm.t)
d <- as.dist(1-d) 
d
plot(hclust(d))
```

##PCA

```{r}
pr <- prcomp(d,scale=TRUE)
plot(pr,type="l",main="Number of Components v. Variance Explained")

library(ggplot2)
scores = as.data.frame(pr$x)
ggplot(data = scores, aes(x = PC1, y = PC2, label = rownames(scores))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(colour = "blue", alpha = 0.8, size = 4) +
  ggtitle("PCA Plot")

rotation <- as.data.frame(pr$rotation)
ggplot(data = rotation, aes(x = PC1, y = PC2, label = rownames(rotation))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(colour = "red", alpha = 0.8, size = 4) +
  ggtitle("PCA Rotation Plot")
```

## MDS

```{r}
mds_scale<- cmdscale(d, k = 2)
fit <- cmdscale(d,eig=TRUE, k=2) # k is the number of dim
fit # view results

# plot solution 
x <- fit$points[,1]
y <- fit$points[,2]
plot(x, y, xlab="Coordinate 1", ylab="Coordinate 2", 
  main="Metric	MDS",	type="n")
text(x, y, labels = row.names(dtms), cex=.7)

```

Estimate K-means clusters

```{r}
set.seed(1234)
clust <- kmeans(dtm.m,2)

# check out clusters
clusters <- clust$cluster
clusters
```
